const BLACKBOARD_ACTION_TYPES = {
    SLIDES_START: "START_SLIDES",
    SLIDES_NEXT: "SLIDES_NEXT",
    SLIDES_END: "SLIDES_END",
    PRACTICE_START: "PRACTICE_START",
    PRACTICE_END: "PRACTICE_END",
    STROOP_START: "STROOP_START",
    STROOP_END: "STROOP_END",
    LOADING_START: "LOADING_START",
    LOADING_COMPLETE: "LOADING_COMPLETE",
    ROUND_NEXT: "ROUND_NEXT",
    SET_PAUSE: "SET_PAUSE",
    SET_MODE: "SET_MODE",
    SET_STARTED: "SET_STARTED",
    SET_CONTENT: "SET_CONTENT",
    SET_COMPLETE: "SET_COMPLETE",
    SET_TIMESTAMP: "SET_TIMESTAMP",
    SLIDES_PREV: "SLIDES_PREV",
    SET_USER_STATE: "SET_USER_STATE",
    SET_FIXATION_MODE: "SET_FIXATION_MODE",
    STROOP_SAVE: "STROOP_SAVE"
}

export default BLACKBOARD_ACTION_TYPES