const STROOP_ROUND_ACTION_TYPES = {
  SET_ROUND: "SET_ROUND",
  SET_KEYPRESS: "SET_KEYPRESS",
  SET_TIME_START: "SET_TIME_START",
  SET_TIME_END: "SET_TIME_END",
  SET_CORRECT: "SET_CORRECT",
  SET_CONGRUENT: "SET_CONGRUENT",
  NO_KEY_PRESS: "NO_KEY_PRESS",
  NEW_ROUND: "NEW_ROUND",
  NEXT_ROUND: "NEXT_ROUND",
};

export default STROOP_ROUND_ACTION_TYPES;
