const USER_SEARCH_ACTION_TYPES = {
    SEARCH_START: "SEARCH_START",
    QUERY_DOC: "QUERY_DOC",
    ERROR: "ERROR",
    LOADING_START: "LOADING_START",
    LOADING_COMPLETE: "LOADING_COMPLETE"
}

export default USER_SEARCH_ACTION_TYPES