export const USER_SEARCH = {
    SEARCH_START: "SEARCH_START",
    QUERY_DOC: "QUERY_DOC",
    ERROR: "ERROR",
    LOADING_START: "LOADING_START",
    LOADING_COMPLETE: "LOADING_COMPLETE"
}

export const STROOP_TEXT = {
    SET_STROOP_TEXT: "SET_STROOP_TEXT",
}

export const BLACKBOARD = {
    SLIDES_START: "START_SLIDES",
    SLIDES_NEXT: "SLIDES_NEXT",
    SLIDES_END: "SLIDES_END",
    PRACTICE_START: "PRACTICE_START",
    PRACTICE_END: "PRACTICE_END",
    STROOP_START: "STROOP_START",
    STROOP_END: "STROOP_END",
    LOADING_START: "LOADING_START",
    LOADING_COMPLETE: "LOADING_COMPLETE",
    ROUND_NEXT: "ROUND_NEXT",
    SET_PAUSE: "SET_PAUSE",
    SET_MODE: "SET_MODE",
    SET_STARTED: "SET_STARTED",
    SET_CONTENT: "SET_CONTENT",
    SET_COMPLETE: "SET_COMPLETE",
    SET_TIMESTAMP: "SET_TIMESTAMP",
    SLIDES_PREV: "SLIDES_PREV",
    SET_USER_STATE: "SET_USER_STATE",
}